# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
script:
# - xctool test -workspace Example/PushbotsLight.xcworkspace -scheme PushbotsLight -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild test -workspace Example/PushbotsLight.xcworkspace -scheme PushbotsLight -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c && exit ${PIPESTATUS[0]}